/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use std::net::IpAddr;

use gtmpl_derive::Gtmpl;
use serde::Deserialize;

pub const PATH: &str = "etc/network/interfaces";
const TMPL_FULL_ETV: &str = include_str!("../templates/interfaces_etv");
const TMPL_EMPTY: &str = "# Auto-generated by Forge!
source /etc/network/interfaces.d/*.intf

auto lo
iface lo inet loopback
";
pub const RELOAD_CMD: &str = "ifreload -a";

/// Generate interfaces file
pub fn build(conf: InterfacesConfig) -> Result<String, eyre::Report> {
    let mut nets = Vec::with_capacity(conf.networks.len());
    for network in conf.networks {
        nets.push(TmplEniConfigPort {
            Name: network.interface_name.clone(),
            VlanID: network.vlan,
            VNI: network.vni,
            IP: network.gateway_cidr.clone(),
        });
    }
    let params = TmplEniConfigParameters {
        LoopbackIP: conf.loopback_ip.to_string(),
        Uplinks: conf.uplinks,
        PortConfigs: nets,
        VNIDevice: conf.vni_device,
    };
    gtmpl::template(TMPL_FULL_ETV, params).map_err(|e| e.into())
}

/// An empty interfaces
pub fn blank() -> String {
    gtmpl::template(TMPL_EMPTY, "").expect("interfaces blank template cannot fail")
}

pub struct InterfacesConfig {
    pub loopback_ip: IpAddr,
    pub uplinks: Vec<String>,
    pub vni_device: String,
    pub networks: Vec<Network>,
}

#[derive(Deserialize, Debug)]
pub struct Network {
    pub interface_name: String,
    pub vlan: u16,
    pub vni: u32,
    pub gateway_cidr: String,
}

//
// Go template objects, hence allow(non_snake_case)
//

#[allow(non_snake_case)]
#[derive(Clone, Gtmpl)]
struct TmplEniConfigParameters {
    LoopbackIP: String,
    Uplinks: Vec<String>,
    PortConfigs: Vec<TmplEniConfigPort>,
    VNIDevice: String,
}

#[allow(non_snake_case)]
#[derive(Clone, Gtmpl)]
struct TmplEniConfigPort {
    Name: String,
    VlanID: u16,
    VNI: u32,
    IP: String, // with mask, 1.1.1.1/20
}
