# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2021-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM runtime-container-localdev:latest as carbide

WORKDIR ./carbide
COPY .skaffold/target/carbide-machine-a-tron/debug/machine-a-tron /opt/machine-a-tron/bin/
COPY crates/machine-a-tron/templates /opt/machine-a-tron/templates

# bmc-mock expects certs here
COPY crates/bmc-mock/tls.crt /opt/carbide/
COPY crates/bmc-mock/tls.key /opt/carbide/
